name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          auto-config: false
          use-github-cache: true
          use-mathlib-cache: true
      - run: lake update
      - run: lake exe cache get || true
      - run: lake build
